### ISSUE TITLE
Fatal error detected: Failed to execute script main

### ISSUE THREAD

**Issue by asifajrof** [mahdihasnat/Screen-Brightness-Controller#1]
how do i actually use this?
i tried using only the exe file. it runs into that error message.

![Fatal error detected
Failed to execute script main](https://i.imgur.com/xXRjsxP.png)

**Comment by mahdihasnat** [comment]
Please try updated latest release again
Or
Setup on your machine and compile to exe

**Comment by asifajrof** [comment]
thanks :)
